name: Project Docs

on: push

jobs:
  quality:
    uses: ./.github/workflows/node-quality.yml
    with:
      eslint-command: yarn lint:ci
      test-command: yarn build
      prettier-command: yarn style

  security:
    uses: ./.github/workflows/node-security.yml
